"""Inspect built archives and enforce the believe14 distribution contract."""

from __future__ import annotations

import argparse
import email.policy
import tarfile
import tomllib
import zipfile
from email.message import Message
from email.parser import BytesParser
from pathlib import Path, PurePosixPath

if __package__:
    from .release_info import ReleaseInfo, load_release_info, project_root
else:  # pragma: no cover - direct script execution
    from release_info import ReleaseInfo, load_release_info, project_root


class DistributionError(RuntimeError):
    """Raised when a built artifact violates the release contract."""


def _safe_archive_names(names: list[str]) -> None:
    for name in names:
        path = PurePosixPath(name)
        if path.is_absolute() or ".." in path.parts:
            raise DistributionError(f"Unsafe archive member: {name!r}")
        if name.endswith((".pyc", ".pyo")) or "__pycache__" in path.parts:
            raise DistributionError(f"Generated bytecode was packaged: {name!r}")


def _metadata(payload: bytes) -> Message:
    return BytesParser(policy=email.policy.default).parsebytes(payload)


def _check_metadata(message: Message, info: ReleaseInfo, root: Path) -> None:
    if message.get("Name") != info.name:
        raise DistributionError(
            f"Metadata Name is {message.get('Name')!r}; expected {info.name!r}."
        )
    if message.get("Version") != info.version:
        raise DistributionError(
            f"Metadata Version is {message.get('Version')!r}; "
            f"expected {info.version!r}."
        )

    document = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))
    project = document["project"]
    if message.get("Requires-Python") != project["requires-python"]:
        raise DistributionError("Requires-Python differs from pyproject.toml.")
    observed_requirements = set(message.get_all("Requires-Dist", []))
    expected_requirements = set(project["dependencies"])
    missing = sorted(expected_requirements - observed_requirements)
    if missing:
        raise DistributionError(f"Core runtime requirements are missing: {missing}")
    if message.get("License-File") != "LICENSE":
        raise DistributionError("Distribution metadata must declare LICENSE.")


def check_wheel(path: Path, info: ReleaseInfo, root: Path) -> None:
    """Validate the wheel filename, metadata, and required package data."""

    if path.name != info.wheel:
        raise DistributionError(f"Unexpected wheel name: {path.name!r}")
    with zipfile.ZipFile(path) as archive:
        names = archive.namelist()
        _safe_archive_names(names)
        metadata_names = [
            name for name in names if name.endswith(".dist-info/METADATA")
        ]
        wheel_names = [name for name in names if name.endswith(".dist-info/WHEEL")]
        if len(metadata_names) != 1 or len(wheel_names) != 1:
            raise DistributionError(
                "Wheel must contain exactly one METADATA and WHEEL."
            )
        _check_metadata(_metadata(archive.read(metadata_names[0])), info, root)
        wheel_metadata = _metadata(archive.read(wheel_names[0]))
        if wheel_metadata.get("Root-Is-Purelib") != "true":
            raise DistributionError("0.1.0 must remain a pure-Python wheel.")
        if "py3-none-any" not in wheel_metadata.get_all("Tag", []):
            raise DistributionError("Wheel must advertise the py3-none-any tag.")
        required_suffixes = (
            "believe14/py.typed",
            ".dist-info/licenses/LICENSE",
        )
        for suffix in required_suffixes:
            if not any(name.endswith(suffix) for name in names):
                raise DistributionError(f"Wheel is missing {suffix}.")


def check_sdist(path: Path, info: ReleaseInfo, root: Path) -> None:
    """Validate the sdist filename, metadata, and release support files."""

    if path.name != info.sdist:
        raise DistributionError(f"Unexpected sdist name: {path.name!r}")
    expected_root = path.name.removesuffix(".tar.gz")
    with tarfile.open(path, mode="r:gz") as archive:
        members = archive.getmembers()
        names = [member.name for member in members]
        _safe_archive_names(names)
        if any(member.issym() or member.islnk() for member in members):
            raise DistributionError(
                "The sdist must not contain symbolic or hard links."
            )
        if any(PurePosixPath(name).parts[0] != expected_root for name in names):
            raise DistributionError("Every sdist member must use the canonical root.")
        metadata_name = f"{expected_root}/PKG-INFO"
        metadata_member = archive.extractfile(metadata_name)
        if metadata_member is None:
            raise DistributionError("The sdist is missing PKG-INFO.")
        _check_metadata(_metadata(metadata_member.read()), info, root)
        required = (
            "README.md",
            "LICENSE",
            "CHANGELOG.md",
            "CITATION.cff",
            "pyproject.toml",
            "Makefile",
            "RELEASING.md",
            "scripts/installed_smoke.py",
            "src/believe14/py.typed",
            "docs/validation/methods.toml",
        )
        present = {name.removeprefix(f"{expected_root}/") for name in names}
        missing = [name for name in required if name not in present]
        if missing:
            raise DistributionError(f"The sdist is missing release files: {missing}")
        ledgers = [
            name
            for name in present
            if name.startswith("docs/validation/")
            and name.endswith(".md")
            and name
            not in {
                "docs/validation/index.md",
                "docs/validation/ledger-template.md",
            }
        ]
        if len(ledgers) != 30:
            raise DistributionError(
                f"The sdist contains {len(ledgers)} method ledgers; expected 30."
            )


def check_dist_directory(
    dist_dir: Path, info: ReleaseInfo, *, allow_extra: bool = False
) -> tuple[Path, Path]:
    """Check that the dist directory contains one canonical wheel and sdist."""

    wheel = dist_dir / info.wheel
    sdist = dist_dir / info.sdist
    missing = [str(path) for path in (wheel, sdist) if not path.is_file()]
    if missing:
        raise DistributionError(f"Missing canonical artifacts: {missing}")
    if not allow_extra:
        archives = {
            path.name
            for path in dist_dir.iterdir()
            if path.is_file()
            and (path.name.endswith(".whl") or path.name.endswith(".tar.gz"))
        }
        expected = {info.wheel, info.sdist}
        if archives != expected:
            raise DistributionError(
                f"dist/ must contain only canonical artifacts; observed={archives}."
            )
    return wheel, sdist


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dist-dir", default=Path("dist"), type=Path)
    parser.add_argument("--allow-extra", action="store_true")
    arguments = parser.parse_args()
    root = project_root()
    info = load_release_info(root)
    wheel, sdist = check_dist_directory(
        arguments.dist_dir, info, allow_extra=arguments.allow_extra
    )
    check_wheel(wheel, info, root)
    check_sdist(sdist, info, root)
    print(f"Distribution metadata and contents are valid for {info.tag}.")


if __name__ == "__main__":
    main()
